[project]
name = "edn-ia"
version = "0.1.0"
description = "Exercises for Escola da Nuvem"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
]
